# Generated by Django 4.1.7 on 2023-02-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='format',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Формат печати'),
        ),
        migrations.AddField(
            model_name='upload',
            name='type_paper',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Тип бумаги'),
        ),
    ]
