# Generated by Django 4.1.7 on 2023-02-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0002_upload_format_upload_type_paper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='format',
            new_name='print_format',
        ),
        migrations.AddField(
            model_name='upload',
            name='folding',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Фальцевание'),
        ),
        migrations.AddField(
            model_name='upload',
            name='number_of_instances',
            field=models.IntegerField(null=True, verbose_name='Кол-во экземпляров'),
        ),
        migrations.AddField(
            model_name='upload',
            name='phone',
            field=models.IntegerField(null=True, verbose_name='Телефон'),
        ),
    ]
