# Generated by Django 4.1.7 on 2023-02-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0003_rename_format_upload_print_format_upload_folding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='bool',
            field=models.BooleanField(null=True, verbose_name='Телефон'),
        ),
    ]
