# Generated by Django 4.1.7 on 2023-02-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0005_alter_upload_bool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='print_format',
            field=models.PositiveSmallIntegerField(choices=[(1, 'A4'), (2, 'A3'), (3, 'A2'), (4, 'A1'), (5, 'A0')], null=True, verbose_name='Формат печати'),
        ),
    ]
