# Generated by Django 4.1.7 on 2023-02-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0006_alter_upload_print_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='folding',
            field=models.PositiveSmallIntegerField(choices=[(1, 'А3'), (2, 'А4')], null=True, verbose_name='Фальцевание'),
        ),
    ]
