# Generated by Django 4.1.7 on 2023-02-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0007_alter_upload_folding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='type_paper',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Обычная'), (2, 'Плотная')], null=True, verbose_name='Тип бумаги'),
        ),
    ]
