# Generated by Django 4.1.7 on 2023-02-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0008_alter_upload_type_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='upload_file',
            field=models.FileField(upload_to='', verbose_name='Перетащите файл'),
        ),
    ]
