# Generated by Django 4.1.7 on 2023-02-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0009_alter_upload_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='print_format',
            field=models.CharField(choices=[(1, 'A4'), (2, 'A3'), (3, 'A2'), (4, 'A1'), (5, 'A0')], max_length=64, null=True, verbose_name='Формат печати'),
        ),
    ]
