# Generated by Django 4.1.7 on 2023-02-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0011_alter_upload_print_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='print_format',
            field=models.CharField(choices=[('A4', 'A4'), ('A3', 'A3'), ('A2', 'A2'), ('A1', 'A1'), ('A0', 'A0')], max_length=64, null=True, verbose_name='Формат печати'),
        ),
    ]
