# Generated by Django 4.1.7 on 2023-02-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0012_alter_upload_print_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='folding',
            field=models.CharField(choices=[('A3', 'А3'), ('A4', 'А4')], max_length=64, null=True, verbose_name='Фальцевание'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='type_paper',
            field=models.CharField(choices=[('usual', 'Обычная'), ('dense', 'Плотная')], max_length=64, null=True, verbose_name='Тип бумаги'),
        ),
    ]
