# Generated by Django 4.1.7 on 2023-02-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0013_alter_upload_folding_alter_upload_type_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='print_format',
            field=models.CharField(choices=[('A4', 'A4'), ('A3', 'A3'), ('A2', 'A2'), ('A1', 'A1'), ('A0', 'A0')], default='A3', max_length=64, null=True, verbose_name='Формат печати'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='type_paper',
            field=models.CharField(choices=[('Обычная', 'Обычная'), ('Плотная', 'Плотная')], max_length=64, null=True, verbose_name='Тип бумаги'),
        ),
    ]
