# Generated by Django 4.1.7 on 2023-02-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0014_alter_upload_print_format_alter_upload_type_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='folding',
            field=models.CharField(blank=True, choices=[('A3', 'А3'), ('A4', 'А4')], max_length=64, null=True, verbose_name='Фальцевание'),
        ),
    ]
