# Generated by Django 3.2.18 on 2023-03-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0018_alter_upload_number_of_instances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='bool',
            field=models.BooleanField(default=False, verbose_name='Да/Нет'),
        ),
    ]
