# Generated by Django 3.2.18 on 2023-03-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0029_alter_upload_bool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='bool',
            field=models.BooleanField(default=None, null=True, verbose_name='Да/Нет'),
        ),
    ]
