# Generated by Django 3.2.18 on 2023-03-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0030_alter_upload_bool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='bool',
            field=models.BooleanField(default=False, null=True, verbose_name='Да/Нет'),
        ),
    ]
