# Generated by Django 3.2.18 on 2023-05-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0031_alter_upload_bool'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='cuser',
            field=models.CharField(blank=True, choices=[('Обычная', 'Обычная'), ('Плотная', 'Плотная')], max_length=64, null=True, verbose_name='Обычная'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='folding',
            field=models.CharField(blank=True, choices=[('A3', 'А3'), ('A4', 'А4'), ('Нет', 'Нет')], max_length=64, null=True, verbose_name='Фальцевание'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='type_paper',
            field=models.CharField(blank=True, choices=[('Обычная', 'Обычная'), ('Плотная', 'Плотная')], max_length=64, null=True, verbose_name='Обычная'),
        ),
    ]
