# Generated by Django 3.2.18 on 2023-05-11 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0032_auto_20230511_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='cuser',
        ),
    ]
