# Generated by Django 3.2.18 on 2023-05-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
